// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sigil.Storage.EfCore;

#nullable disable

namespace Sigil.Storage.EfCore.Migrations
{
    [DbContext(typeof(SigilDbContext))]
    [Migration("20260510134223_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sigil.Core.Audit.AuditEntry", b =>
                {
                    b.Property<string>("AuditId")
                        .HasColumnType("text")
                        .HasColumnName("audit_id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.HasKey("AuditId");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_audit_entries_agent_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_audit_entries_job_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_entries_timestamp");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Sigil.Core.Checkpoints.Checkpoint", b =>
                {
                    b.Property<string>("CheckpointId")
                        .HasColumnType("text")
                        .HasColumnName("checkpoint_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("text")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_id");

                    b.HasKey("CheckpointId");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_checkpoints_job_id");

                    b.ToTable("checkpoints", (string)null);
                });

            modelBuilder.Entity("Sigil.Core.Jobs.Job", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("JobId");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Sigil.Core.Registry.AgentRegistration", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint_url");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_heartbeat");

                    b.Property<int?>("MaxTokenBudget")
                        .HasColumnType("integer")
                        .HasColumnName("max_token_budget");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("registered_at");

                    b.Property<int>("RoutingWeight")
                        .HasColumnType("integer")
                        .HasColumnName("routing_weight");

                    b.Property<string>("SemanticVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semantic_version");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tools")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tools");

                    b.HasKey("AgentId");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_agent_registrations_domain");

                    b.HasIndex("Skills")
                        .HasDatabaseName("ix_agent_registrations_skills_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Skills"), "gin");

                    b.ToTable("agent_registrations", (string)null);
                });

            modelBuilder.Entity("Sigil.Storage.EfCore.Persistence.ContextStateRecord", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etag");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("log");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.HasKey("JobId");

                    b.ToTable("context_states", (string)null);
                });

            modelBuilder.Entity("Sigil.Core.Audit.AuditEntry", b =>
                {
                    b.OwnsOne("Sigil.Core.Protocol.ContextDelta", "Delta", b1 =>
                        {
                            b1.Property<string>("AuditEntryAuditId")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string>("Removals")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("delta_removals");

                            b1.Property<string>("Updates")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("delta_updates");

                            b1.HasKey("AuditEntryAuditId");

                            b1.ToTable("audit_entries");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryAuditId");
                        });

                    b.OwnsOne("Sigil.Core.Protocol.UsageMetrics", "Metrics", b1 =>
                        {
                            b1.Property<string>("AuditEntryAuditId")
                                .HasColumnType("text");

                            b1.Property<long>("CompletionTokens")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_completion_tokens");

                            b1.Property<string>("Custom")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("metrics_custom");

                            b1.Property<long>("Duration")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_duration_ticks");

                            b1.Property<long>("PromptTokens")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_prompt_tokens");

                            b1.HasKey("AuditEntryAuditId");

                            b1.ToTable("audit_entries");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryAuditId");
                        });

                    b.Navigation("Delta")
                        .IsRequired();

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("Sigil.Core.Registry.AgentRegistration", b =>
                {
                    b.OwnsOne("Sigil.Core.Registry.AgentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<string>("AgentRegistrationAgentId")
                                .HasColumnType("text");

                            b1.Property<string>("Tags")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("metadata_tags");

                            b1.HasKey("AgentRegistrationAgentId");

                            b1.ToTable("agent_registrations");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationAgentId");
                        });

                    b.OwnsOne("Sigil.Core.Registry.ModelSpec", "Model", b1 =>
                        {
                            b1.Property<string>("AgentRegistrationAgentId")
                                .HasColumnType("text");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("model_name");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("model_provider");

                            b1.HasKey("AgentRegistrationAgentId");

                            b1.ToTable("agent_registrations");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationAgentId");

                            b1.OwnsOne("Sigil.Core.Registry.Sampling", "Sampling", b2 =>
                                {
                                    b2.Property<string>("ModelSpecAgentRegistrationAgentId")
                                        .HasColumnType("text");

                                    b2.Property<int?>("MaxOutputTokens")
                                        .HasColumnType("integer")
                                        .HasColumnName("model_max_output_tokens");

                                    b2.Property<double?>("Temperature")
                                        .HasColumnType("double precision")
                                        .HasColumnName("model_temperature");

                                    b2.Property<double?>("TopP")
                                        .HasColumnType("double precision")
                                        .HasColumnName("model_top_p");

                                    b2.HasKey("ModelSpecAgentRegistrationAgentId");

                                    b2.ToTable("agent_registrations");

                                    b2.WithOwner()
                                        .HasForeignKey("ModelSpecAgentRegistrationAgentId");
                                });

                            b1.Navigation("Sampling")
                                .IsRequired();
                        });

                    b.OwnsOne("Sigil.Core.Registry.SecurityProfile", "Security", b1 =>
                        {
                            b1.Property<string>("AgentRegistrationAgentId")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string>("AllowedTools")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("security_allowed_tools");

                            b1.Property<string>("CertificateThumbprint")
                                .HasColumnType("text")
                                .HasColumnName("security_cert_thumbprint");

                            b1.Property<bool>("IsPiiCleared")
                                .HasColumnType("boolean")
                                .HasColumnName("security_is_pii_cleared");

                            b1.Property<string>("SigilKey")
                                .HasColumnType("text")
                                .HasColumnName("security_sigil_key");

                            b1.Property<string>("Tier")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("security_tier");

                            b1.HasKey("AgentRegistrationAgentId");

                            b1.ToTable("agent_registrations");

                            b1.WithOwner()
                                .HasForeignKey("AgentRegistrationAgentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Model")
                        .IsRequired();

                    b.Navigation("Security")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
